### ISSUE TITLE
Hola, donde puedo dormir?

### ISSUE THREAD

**Issue by mariaperezcatalan** [berlanga/SemanticBots#15]
Morella:  "Donde puedo dormir?" funciona, pero si delante le ponemos "Hola", no funciona. Este tipo de ejemplos será muy frecuente....

Podemos considerar solo lo último o despreciar ciertas entidades que sean meaningless?

**Comment by berlanga** [comment]
De momento está resuelto, aunque no generalizado. Aún está abierto el tema de "multi-intent", donde la misma sentencia expresa más de una intención.
Aquí el problema es detectar dónde empieza la pregunta (ASKQ). Si la partícula interrogativa no está al principio podría etiquetarse como coordinador (COOR) en lugar de ASKQ. Esta disyuntiva se resuelve ahora en tagFocus, donde los elementos COOR pueden convertirse en ASQK si todos los elementos anteriores eran "meaningless".
