### ISSUE TITLE
Ajuntament - Bicicletas

### ISSUE THREAD

**Issue by mariaperezcatalan** [berlanga/SemanticBots#19]
31-3-2021
**VALIDACIÓN AUTOMÁTICA:** 

- Hay unas cuántas faqs que van a la misma pregunta errónea "Cuánto tiempo puedo reservar", y no tengo ni idea porqué.

-Algo funciona mal: Porque en la consola si que sale la respuesta correcta (2CaKzt:3:ANSW)  pero luego devuelve una que no es correcta (IMP8t:_:ANSW)
![image](https://user-images.githubusercontent.com/79442722/113158287-f4a34a80-923b-11eb-948d-b6b30cc69751.png)

**IDIOMAS**
Solo está en castellano.

**Comment by berlanga** [comment]
Solucionado. El problema es que tenía un grafo indexando las respuestas y estaba interfiriendo con el grafo de las preguntas (que es el que tiene  que activarse).
