### ISSUE TITLE
Valenciano

### ISSUE THREAD

**Issue by mariaperezcatalan** [berlanga/SemanticBots#2]
#l·l  --> Pone directamente ll. Ejemplo "sollicitud"  . ¿Hay alguna forma de detectarlo sin tener que estar mirando una a una?

"_" --> Cuando no traduce una palabra, pone "_" delante de la palabra.  ¿Hay alguna forma de detectarlo sin tener que estar mirando una a una?

**Comment by berlanga** [comment]
Si es culpa del traductor automático podemos corregir estas faltas a posteriori siempre y cuando estén en el diccionario. El problema de las "ll" podría resolverse con el diccionario.

Del segundo problema: podemos guardar todas las palabras no traducidas (y los CUIs dónde ocurren). Cuando haya una traducción de esas palabras se cambia el texto del CUI correspondiente. ¿Te parece bien así?  ¿ o te refieres a otra cosa?

**Comment by mariaperezcatalan** [comment]
Me parece perfecto las dos cosas: resolución con el diccionario y lo de registrar las palabras no traducidas y los cuis donde ocurren y así poder ir directamente y no ir mirando una a una.
