### ISSUE TITLE
que puc fer a Morella amb xiquets?

### ISSUE THREAD

**Issue by mariaperezcatalan** [berlanga/SemanticBots#7]
No hay manera de que anota "amb xiquets". He intentado añadirlo como traducción de niños, pero nada.  "Què puc fer a morella amb nens?" funciona pero anota "amb nens" y tampoco sé como poner "amb xiquets" como sinónimo.

**Comment by berlanga** [comment]
"xiquets" ya tenía un CUI is diferente a "con niños". "amb xiquets" no estaba, lo he metido a mano y ya parece que funciona.
